### PR TITLE
basic test cases, not all succeed

### PR DESCRIPTION
**Pull request by Jkozmo10**

### CODE REVIEW

**Review by ynozar — CHANGES_REQUESTED** [review]
Good work on the Unit tests but let's touch base on adding our Mongo Credentials to our workflow so that it will be able to run the tests for us

**Review by ConnorDye — COMMENTED** [review]
Looks good nice tests!  So for the users, we're having the date be the key to each entry correct? I pasted my question below:

 user ={ 
    _id: 'testsubject',
    name: 'testname',
    subject: 'testsubject',
    userProfile: 'testprofile',
    diary: { "10-11-2022": {
      "date": "10-11-2022",
      "title": "My First Entry",
      "text": "I had a great day!",
      "rating": 10,
      "_id": "6370958140cb4709d8981449"
  }},

**Review by jeremiahpino — COMMENTED** [review]
Great job Jeremy! Looks like you are close to finishing all test cases to test back end functionality. Well done!

**Review by ynozar — APPROVED** [review]

**Comment by ynozar** [comment]
> Good work on the Unit tests but let's touch base on adding our Mongo Credentials to our workflow so that it will be able to run the tests for us
Thanks for adding the Mongo Credentials! I see the tests are passing on some node versions. I think we are running into issues with concurrent calls to the database let me see if we can tell github actions to test only on the version of node we are using

**Review by ConnorDye — APPROVED** [review]
Approved. See last comment for review.

**Comment by Jkozmo10** [comment]
> Good work on the Unit tests but let's touch base on adding our Mongo Credentials to our workflow so that it will be able to run the tests for us

Done.

**Comment by Jkozmo10** [comment]
> Looks good nice tests! So for the users, we're having the date be the key to each entry correct? I pasted my question below:
> 
> user ={ _id: 'testsubject', name: 'testname', subject: 'testsubject', userProfile: 'testprofile', diary: { "10-11-2022": { "date": "10-11-2022", "title": "My First Entry", "text": "I had a great day!", "rating": 10, "_id": "6370958140cb4709d8981449" }},

Hey @ConnorDye , so we have a diary field in the overall user. The diary field is a map that uses dates as keys and entries as the values. I hope this cleared up any confusion!

**Review by jeremiahpino — APPROVED** [review]
LGTM! Great job in designing the schema of our database!

**Pull request merged**
